// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsknE1XDz9LZHIGuqtdyAlG0MXyu1HsqQ',
    appId: '1:129003196230:web:aa4b912d1608f876611f47',
    messagingSenderId: '129003196230',
    projectId: 'insta-app-ec2cb',
    authDomain: 'insta-app-ec2cb.firebaseapp.com',
    storageBucket: 'insta-app-ec2cb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbhuAMVyOhYLyzP6Xe44wgLGi5VZkU8o8',
    appId: '1:129003196230:android:31e2e2e8d29f9415611f47',
    messagingSenderId: '129003196230',
    projectId: 'insta-app-ec2cb',
    storageBucket: 'insta-app-ec2cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIOAEkKQslIbyhhtVnTPkfhvtONCnR_Do',
    appId: '1:129003196230:ios:bb0c8693ade61e6d611f47',
    messagingSenderId: '129003196230',
    projectId: 'insta-app-ec2cb',
    storageBucket: 'insta-app-ec2cb.appspot.com',
    iosBundleId: 'com.example.flutterInsta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIOAEkKQslIbyhhtVnTPkfhvtONCnR_Do',
    appId: '1:129003196230:ios:12bf3648d78f30ee611f47',
    messagingSenderId: '129003196230',
    projectId: 'insta-app-ec2cb',
    storageBucket: 'insta-app-ec2cb.appspot.com',
    iosBundleId: 'com.example.flutterInsta.RunnerTests',
  );
}
